---
version: '3.4'
services:
  weaviate-rbac:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8085'
      - --scheme
      - http
      - --write-timeout=600s
    image: semitechnologies/weaviate:${WEAVIATE_VERSION}
    ports:
      - 8091:8085
      - 50062:50051
    restart: on-failure:0
    environment:
      ENABLE_MODULES: "generative-dummy,reranker-dummy"
      PERSISTENCE_DATA_PATH: "./data-weaviate-0"
      CLUSTER_IN_LOCALHOST: "true"
      CLUSTER_GOSSIP_BIND_PORT: "7100"
      CLUSTER_DATA_BIND_PORT: "7101"
      RAFT_BOOTSTRAP_EXPECT: "1"
      AUTHENTICATION_APIKEY_ENABLED: "true"
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: 'viewer-key,editor-key,admin-key,custom-key'
      AUTHENTICATION_APIKEY_USERS: 'viewer-user,editor-user,admin-user,custom-user'
      AUTHORIZATION_RBAC_ENABLED: "true"
      AUTHORIZATION_ADMIN_USERS: "admin-user"
      AUTHORIZATION_VIEWER_USERS: "viewer-user"
...
